@startuml
left to right direction
actor "Projektentwickler: in" as fc
rectangle Cloud-Infrastruktur {
  usecase "Firewall" as UC1
  usecase "Login \nNginx Reverse Proxy Manager" as UC2
  UC1 ..> (Authelia) : <<include>>
  UC2 ..> (Authelia) : <<include>>
  UC2 <.. (Dienste) : <<extends>>
  (Dienste) <.. (Authelia) : <<extends>>
}
fc --> UC1
fc --> UC2
@enduml